apiVersion: v1
kind: Pod
metadata:
  name: jellyseer
spec:
  containers:
  - name: jellyseer
    image: docker.io/fallenbagel/jellyseerr
    ports:
    - hostPort: 5055
    env:
    - name: TZ
      value: Etc/UTC
    - name: LOG_LEVEL
      value: debug
    volumeMounts:
    - name: config
      mountPath: /config:Z
  volumes:
  - name: config
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/jellyseer/config
      type: DirectoryOrCreate
