apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent
spec:
  containers:
  - name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    ports:
    - hostPort: 8070
    - protocol: TCP
      hostPort: 6881
    - protocol: UDP
      hostPort: 6881
    env:
    - name: TZ
      value: Etc/UTC
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000
    - name: WEBUI_PORT
      value: 8070
    volumeMounts:
    - name: config
      mountPath: /config:Z
    - name: storage
      mountPath: /storage/torrents:z
  volumes:
  - name: config
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/qbittorrent/config
      type: DirectoryOrCreate
  - name: storage
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/storage/torrents
