apiVersion: v1
kind: Pod
metadata:
  name: bazarr
  annotations:
    io.containers.autoupdate: registry
spec:
  containers:
  - name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
    - hostPort: 6767
    env:
    - name: TZ
      value: Etc/UTC
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000
    volumeMounts:
    - name: config
      mountPath: /config:Z
    - name: movies
      mountPath: /movies:z
    - name: tv
      mountPath: /tv:z
  volumes:
  - name: config
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/bazarr/config
      type: DirectoryOrCreate
  - name: movies
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/storage/media/movies
  - name: tv
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/storage/media/tvshows
