version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5  # optional - set the autodiscovery response domain or IP address
    volumes:
      - ~/Auxiliary/Trackers/jellyfin/config:/config:Z
      - ~/Auxiliary/Trackers/storage/media:/data:z
    ports:
      - 8096:8096  # http UI
      # - 8920:8920  # optional - https UI
      - 7359:7359/udp  # optional - discover server on local network
      - 1900:1900/udp  # optional - service discovery used by DNLA and client
    restart: unless-stopped
