apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
  annotations:
    io.containers.autoupdate: registry
spec:
  containers:
  - name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
    - hostPort: 8096
    env:
    - name: TZ
      value: Etc/UTC
    - name: PUID
      value: 1000
    - name: PGID
      value: 1000
    - name: JELLYFIN_PublishedServerUrl
      value: 192.168.0.5  # optional - set the autodiscovery response domain or IP address
    volumeMounts:
    - name: config
      mountPath: /config:Z
    - name: storage
      mountPath: /data:z
  volumes:
  - name: config
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/jellyfin/config
      type: DirectoryOrCreate
  - name: storage
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/storage/media
