apiVersion: v1
kind: Pod
metadata:
  name: portainer
  annotations:
    io.containers.autoupdate: registry
spec:
  securityContext:
    seLinuxOptions:
      type: spc_t  # equivalent to --security-opt label=disable
  containers:
  - name: portainer
    image: docker.io/portainer/portainer-ce:latest
    ports:
    - hostPort: 9443
    volumeMounts:
    - name: data
      mountPath: /data:Z
    - name: socket
      mountPath: /var/run/docker.sock:z
  volumes:
  - name: data
    hostPath:
      path: /home/xph8/Auxiliary/Trackers/portainer
      type: DirectoryOrCreate
  - name: socket
    hostPath:
      path: /run/user/1000/podman/podman.sock
