version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8070
    volumes:
      - ~/Auxiliary/Trackers/qbittrorrent/config:/config:Z
      - ~/Auxiliary/Trackers/storage/torrents:/storage/torrents:z
    ports:
      - 8070:8070
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
